import java.sql.*;
import javax.swing.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NAFEESATH MISBHA
 */
public class Doctor extends javax.swing.JFrame {

    /**
     * Creates new form hello
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdoctor = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdspec = new javax.swing.JTextField();
        txtdgender = new javax.swing.JTextField();
        txtdname = new javax.swing.JTextField();
        txtdid = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("DOCTOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 39, -1, -1));

        jButton2.setText("LOAD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 506, -1, -1));

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 506, -1, -1));

        jButton4.setText("INSERT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 506, -1, -1));

        tdoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DID", "DNAME", "DGENDER", "DSPEC"
            }
        ));
        jScrollPane1.setViewportView(tdoctor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 129, 704, 147));

        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 566, -1, -1));

        jButton6.setText("ADD NEW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 506, -1, -1));

        jButton1.setText("RETRIEVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 506, -1, -1));

        jLabel1.setText("DID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 360, -1, -1));

        jLabel2.setText("DNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 400, -1, -1));

        jLabel3.setText("DGENDER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 440, -1, -1));

        jLabel4.setText("DSPEC");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 477, -1, -1));

        txtdspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdspecActionPerformed(evt);
            }
        });
        getContentPane().add(txtdspec, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 477, 399, -1));
        getContentPane().add(txtdgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 437, 399, -1));

        txtdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 397, 399, -1));

        txtdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdidActionPerformed(evt);
            }
        });
        getContentPane().add(txtdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 357, 399, -1));

        jButton7.setText("MAIN MENU");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 506, -1, -1));

        jButton8.setText("UPDATE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 506, -1, -1));

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 566, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 760, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model=(DefaultTableModel)tdoctor.getModel();
        model.setRowCount(0);
        txtdid.setText("");
        txtdname.setText("");
        txtdgender.setText("");
        txtdspec.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con;
        Statement st;
        ResultSet rs;
        try
        {
            DefaultTableModel model=(DefaultTableModel)tdoctor.getModel();
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","A1b2c3#4");
            st=con.createStatement();
            rs=st.executeQuery("select * from DOCTOR");
            while(rs.next())
            {
                String DID=rs.getString("DID");
                String DNAME=rs.getString("DNAME");
                String DGENDER=rs.getString("DGENDER");
                String DSPEC=rs.getString("DSPEC");
                Object d[]={DID,DNAME,DGENDER,DSPEC};
                model.addRow(d);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY:"+e.getMessage());
        }      //TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdspecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdspecActionPerformed

    private void txtdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con;
        Statement st;
        ResultSet rs;
        try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","A1b2c3#4");
            st=con.createStatement();
            rs=st.executeQuery("select * from DOCTOR where DID= "+txtdid.getText());
            while(rs.next())
            {
                String DID=rs.getString("DID");
                String DNAME=rs.getString("DNAME");
                String DGENDER=rs.getString("DGENDER");
                String DSPEC=rs.getString("DSPEC");
                
                txtdid.setText(DID);
                txtdname.setText(DNAME);
                txtdgender.setText(DGENDER);
                txtdspec.setText(DSPEC);
                
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY:"+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"ARE YOU SURE YOU WANT TO EXIT?");
        if(a==0)
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        txtdid.setText("");
        txtdname.setText("");
        txtdgender.setText("");
        txtdspec.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Connection con;
        Statement st;
        ResultSet rs;
        try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","A1b2c3#4");
            st=con.createStatement();
            st.executeUpdate("insert into DOCTOR values("+txtdid.getText()
                +",'"+txtdname.getText()+"','"+
                txtdgender.getText()+"','"
                +txtdspec.getText()+"');");
            DefaultTableModel model=(DefaultTableModel)tdoctor.getModel();
            JOptionPane.showMessageDialog(null,"new doctor added succesfully");
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Admin f1=new Admin();
        f1.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       Connection con;
        Statement st;
        ResultSet rs;
        try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","A1b2c3#4");
            st=con.createStatement();
            String query= "update DOCTOR set DID='"+txtdid.getText()
            +"',DNAME='"+txtdname.getText()
            +"',DGENDER='"+txtdgender.getText()
            +"',DSPEC='"+txtdspec.getText()
            +"'where DID="+txtdid.getText()+";";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"doctor updated succesfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY:"+e.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      Connection con;
        Statement st;
        ResultSet rs;
        try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","A1b2c3#4");
            st=con.createStatement();
            String query= "DELETE FROM DOCTOR WHERE DID='" + txtdid.getText() + "';";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"doctor deleted succesfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY:"+e.getMessage());
        } 
    }//GEN-LAST:event_jButton9ActionPerformed
                  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tdoctor;
    private javax.swing.JTextField txtdgender;
    private javax.swing.JTextField txtdid;
    private javax.swing.JTextField txtdname;
    private javax.swing.JTextField txtdspec;
    // End of variables declaration//GEN-END:variables
}
